"""SwitchDoor: a deterministic hidden-rule visual environment."""

from .core import (
    ACTION_DELTA,
    ALL_RULES,
    C0,
    C1,
    C2,
    C3,
    Action,
    Color,
    DoorResponse,
    Episode,
    Position,
    RuleClass,
    RuleConfig,
    SwitchMapping,
    WorldSpec,
    WorldState,
    compatible_rules,
    execute,
    initial_state,
    parse_rule_json,
    reachable_states,
    step,
)
from .dataset import audit_dataset, load_private_episodes, materialize_dataset
from .env import SwitchDoorEnv, Transition
from .generation import (
    ActionFamily,
    GenerationConfig,
    LayoutFamily,
    ScenarioGroup,
    ScenarioShell,
    audit_scenario_group,
    build_scenario_group,
    build_shell,
    generate_scenario_groups,
)
from .planning import oracle_shortest_plan
from .rendering import render_png, render_rgb, write_rendered_png

__version__ = "0.1.0"

__all__ = [
    "ACTION_DELTA",
    "ALL_RULES",
    "C0",
    "C1",
    "C2",
    "C3",
    "Action",
    "ActionFamily",
    "Color",
    "DoorResponse",
    "Episode",
    "GenerationConfig",
    "LayoutFamily",
    "Position",
    "RuleClass",
    "RuleConfig",
    "ScenarioGroup",
    "ScenarioShell",
    "SwitchDoorEnv",
    "SwitchMapping",
    "Transition",
    "WorldSpec",
    "WorldState",
    "audit_dataset",
    "audit_scenario_group",
    "build_scenario_group",
    "build_shell",
    "compatible_rules",
    "execute",
    "generate_scenario_groups",
    "initial_state",
    "load_private_episodes",
    "materialize_dataset",
    "oracle_shortest_plan",
    "parse_rule_json",
    "reachable_states",
    "render_png",
    "render_rgb",
    "step",
    "write_rendered_png",
]
